name: Backend CI

on:
  push:
    branches: [ dev, main, feature/** ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint and format
        run: |
          cd backend
          # Example: run flake8/black (configure in future)
          echo "No lint configured yet"

      - name: Run tests
        run: |
          cd backend
          pytest --maxfail=1 --disable-warnings || true

      - name: Build Docker image
        run: |
          echo "Docker build step (to be configured)"

      - name: Upload coverage
        if: always()
        run: echo "Upload coverage report to Codecov/coverage service if configured"
