name: Frontend CI

on:
  push:
    branches: [ dev, main, feature/** ]
  pull_request:
    branches: [ dev ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          cd frontend
          if [ -f yarn.lock ]; then yarn install --frozen-lockfile; else npm install; fi

      - name: Lint and Test
        run: |
          cd frontend
          # Example: run ESLint and Jest (configure in future)
          echo "No frontend tests configured yet"

      - name: Build App
        run: |
          cd frontend
          # Example: build Expo or React Native project for staging
          echo "Build step to be configured (e.g. expo build)"
